# Generated by Django 3.0.7 on 2020-06-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='url_af',
            field=models.CharField(default='', max_length=200),
        ),
    ]
