# Generated by Django 3.0.7 on 2020-06-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20200617_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='url_af',
            field=models.URLField(default=''),
        ),
    ]
